name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make -f ./introduction/python-scaffold/Makefile install
      - name: Check for PEP8 violations
        run: |
          make -f ./introduction/python-scaffold/Makefile format-checks
      - name: Analysing the code with pylint
        run: |
          make -f ./introduction/python-scaffold/Makefile lint
      - name: Test code coverage with pytest
        run: |
          make -f ./introduction/python-scaffold/Makefile test
